### ISSUE TITLE
Not available on WP Plugin Library

### ISSUE THREAD

**Issue by amirsameny** [daart-agency/DaartAds-WP#7]
Hello,
As I saw it's not available for download on `WPPL`.

**Comment by aljvdi** [comment]
Hi there,
Your assertion is true; we have updated this version, which is currently available for download from the WordPress library.
Regarding for the download, the direct link to the WordPress is: `https://wordpress.org/plugins/daart-ads/`.

P.S. Additionally, I will update the "README.md" with the WP link.
